from array import *
arr=array("i",[10,20,30,40,50])
arr.append(30)
arr.append(40)
print("after appending 30 and 40 ",arr)
arr.insert(1,99)
print("after inserting 99 at pos 1st",arr)
arr.remove(20)
print("after removing 20",arr)
n=arr.pop()
print("array after using pop():method",arr)
print("popped element",n)
n=arr.index(30)
print("first occurence of element of 30 is at:",n)
lst=arr.tolist()
print("list:",lst)
print("array",arr)
