from numpy import *
arr=array([10,289,3,98,90])
print("original array",arr)
print("after adding +5",arr+5)
print("after subtracting -5",arr-5)
print("after subtracting -5",arr-5)
print("after multiplication 2",arr*2)
print("after dividing 5",arr/5)
print("after modulus 5",arr%5)

print("expression Value :",(arr+5)**2-10)
print("sin values:",sin(arr))
print("cos values:",cos(arr))
print("tan values:",tan(arr))
print("biggest values:",max(arr))
print("min values:",min(arr))
print("mean values:",mean(arr))
print("sum values:",sum(arr))
print("sorting element",sort(arr))
print(arr)
