str=input("enter hexadecimal number:")
n=int(str,16)
print("hexadecimal to decimal",n)
str=input("octal number ")
n=int(str,8)
print("octal to decimal number",8)
str=input("enter binary number:")
n=int(str,2)
print("binary to decimal",n)

