str=input("Enter hexadecimal number:")
n=int(str,16)
print("hexadecimal  to decimal=",n)
str=input("Enter octal number")
n=int(str,8)
print("octal to decimal:",n)
str=input("enter binary number:")
n=int(str,2)
print("binary to decimal=",n)
